name: opensyllabus
channels:
  - defaults
  - anaconda
  - conda-forge
dependencies:
  - python=3.7
  - click
  - requests
  - pandas
  - scikit-learn
  - pytorch
  - torchtext
  - pip
  - pip:
    - mlflow